### ISSUE TITLE
Can't integrate my gmail account of todoist in RemNote

### ISSUE THREAD

**Issue by ynopilapil** [YouriLieverdink/remnote_todoist_plugin#1]
Hi! Whenever I try to log in my todoist account in gmail in RemNote, it always shows up as "invalid CSRF token". How can I fix this? Thanks

**Comment by Tiago9632** [comment]
I'm having the same issue.

**Comment by YouriLieverdink** [comment]
I changed the implementation of the plugin and now you're able to use the `Todoist` powerup to directly insert a list of tasks into Remnote. I'll be updating the README a little later with some instructions
